emp_name=input("enter a employee name")
emp_id=int(input("enter a employee id"))
emp_phoneno=int(input("enter a employee phone no"))
emp_adress=input("enter a employee adress")
emp_salaray=int(input("enter a employee salary"))
print(emp_name)
print(emp_id)
print(emp_phoneno)
print(emp_adress)
print(emp_salary)
                       
